name: BetterRanks
version: '3.1.0-SNAPSHOT'
main: betterbox.mine.game.betterranks.BetterRanks
api-version: '1.18'
author: 'grzybol'

commands:
  br:
    description: Manage player ranks and codes.
    usage: |
      /<command> tl
      /<command> code <code>
    aliases: [betranks, setrank]
  info:
    description: Plugin info.
  debug:
    description: Toggles debug
    permission: betterranks.command.debug
  add:
    usage:
      /<command> add <player> <rank> <amount> <s/m/d>
    description: Add a rank to a player.
    permission: betterranks.command.add
  delete:
    usage:
      /<command> delete <player>
    description: Delete a player's rank.
    permission: betterranks.command.delete
  createcode:
    description: Create codes for ranks.
    permission: betterranks.command.createcode
  code:
    description: Use a code.
    permission: betterranks.command.code
  tl:
    description: Check remaining time.
    permission: betterranks.command.tl

permissions:
  betterranks.command.br:
    description: Allows usage of the /br command.
    default: op
  betterranks.command.add:
    description: Allows adding a rank to a player.
    default: op
  betterranks.command.delete:
    description: Allows deleting a player's rank.
    default: op
  betterranks.command.createcode:
    description: Allows creating codes for ranks.
    default: op
  betterranks.command.code:
    description: Allows reedeming the code.
    default: op
  betterranks.command.tl:
    description: Allows to check remaining time.
    default: op
  betterranks.command.debug:
    description: Allows to toggle debug.
    default: op

