name: BetterRanks
version: '4.3.23-SNAPSHOT'
main: betterbox.mine.game.betterranks.BetterRanks
api-version: '1.18'
author: 'grzybol'
description: 'Plugin for managin ranks'
depend: [GroupManager]

commands:
  br:
    description: Manage player ranks and codes.
    usage: |
      /br tl
      /br code <code>
    aliases: [betranks, setrank]
  info:
    description: Plugin info.
    aliases: [help, h]
  debug:
    description: Toggles debug
    permission: betterranks.command.debug
  add:
    usage:
      /br add <player> <rank> <time_amount> <s/m/d>
    description: Add a rank to a player.
    permission: betterranks.command.add
  delete:
    usage:
      /br delete <player>
    description: Delete a player's rank.
    permission: betterranks.command.delete
  createcode:
    description: Create codes for ranks under given pool name. Each user can redeem only one code per pool.
    usage:
      /br createcode <quantity> <rank> <time_amount> <s/m/d> <pool_name>
    permission: betterranks.command.createcode
  code:
    description: Use a code.
    usage:
      /br code <code>
    permission: betterranks.command.code
  tl:
    description: Check remaining time.
    usage:
      /br tl
    permission: betterranks.command.tl
  reload:
    description: Reloads config gile
    usage:
      /br reload
    permission: betterranks.command.reload

permissions:
  betterranks.command.br:
    description: Allows usage of the /br command.
    default: op
  betterranks.command.add:
    description: Allows adding a rank to a player.
    default: op
  betterranks.command.delete:
    description: Allows deleting a player's rank.
    default: op
  betterranks.command.createcode:
    description: Allows creating codes for ranks.
    default: op
  betterranks.command.code:
    description: Allows redeeming the code.
    default: op
  betterranks.command.tl:
    description: Allows to check remaining time.
    default: op
  betterranks.command.debug:
    description: Allows to toggle debug.
    default: op
  betterranks.command.reload:
    description: Reloads config file
    default: op


